databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails server
    preDeployCommand: "bundle exec rails db:migrate"

    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: MYAPP_DATABASE_USER
        sync: false
      - key: MYAPP_DATABASE_PASSWORD
        sync: false
      - key: DATABASE_HOST
        sync: false  # Optional, if you want to define a specific host
