# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: rental_development

test:
  <<: *default
  database: rental_test

production:
  <<: *default
  # No need to specify database, username, and password here, as DATABASE_URL will provide them.
