default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: estate_management_development

test:
  <<: *default
  database: estate_management_test

production:
  <<: *default
  database: estate_management_production
  username: estate_management
  password: <%= ENV['ESTATE_MANAGEMENT_DATABASE_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Full connection URL for production
