# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mumbere

development:
  <<: *default
  database: rental_development

test:
  <<: *default
  database: rental_test

# production:
#   <<: *default
#   database: rental_production
#   username: <%= ENV['MYAPP_DATABASE_USER'] %>
#   password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>


  production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: rental_production
  username: my_app_render
  password: <%= ENV['MY_APP_RENDER_DATABASE_PASSWORD'] %>
